Fix
ShinyParadise/ToDoList pull request #3
Opened 2022-07-28 12:56 UTC by ShinyParadise

2022-07-28 13:29 UTC, menteValidus requested changes

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +        ListModel listModel = new ListModel();
Почемы ты создаёшь пустую сущность именно здесь?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +            }
У тебя здесь дублирование кода. Как от него избавиться?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
>                  listItems.add(newListItem);
Такая же проблема, как и выше.

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
> +        String newStateString = (listItem.is_checked) ? "1" : "0";
По-хорошему твоя сущность, которая изпользуется в связке с БД, должна быть уже полностью готова к записе. В этой строчке происходит нарушение одного из принципов SOLID. Какого?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
> +        listItemModel.is_checked = request.getInt(2) != 0;
Та же проблема, что и выше.

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/DatabaseContract.java
> +                + COLUMN_IS_CHECKED + " = (?) WHERE " + _ID + " = (?);";
https://www.javatpoint.com/java-string-format для такого лучше использовать строку форматирования.

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +    }
У тебя использвются все конструкторы?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListModel.java
> +    }
Что произойдёт, если я сделаю:
`ListModel().header;`

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +        }
Возможно ли эту логику куда-нибудь вынести?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +        );
Можно ли эту логику куда-нибудь выннести?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +    public void insertListItem(int listID, String listItemDescription) {
Можно ли сделать так, чтобы id назначалось БД, а не в приложении?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +    public void insertListItem(int listID, String listItemDescription) {
И чем плохо, если задача назначение ID лежит на приложении?

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listrepository/ListRepository.java
>  public class ListRepository implements IListRepository {
В основном те же комментарии, что и на прошлом репозитории.

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/detailscreen/DetailedListViewModel.java
> +import com.example.todolist.repositories.listrepository.IListRepository;
В названии пакетов мы используем lowerCamelCase.
```suggestion
import com.example.todolist.repositories.listRepository.IListRepository;
```

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/detailscreen/DetailedListViewModel.java
> +                                 String listHeader) {
Если мы имеем `listId`, можем ли мы через него получить `listHeader`.

2022-07-28 13:29 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/listscreen/ListViewModel.java
>      }
Нарушаешь ли ты здесь последнюю букву SOLID?

2022-07-29 10:22 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +            }
Вынести в отдельный метод

2022-07-29 10:25 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
> +        String newStateString = (listItem.is_checked) ? "1" : "0";
Нарушен принцип единственной ответственности. ДАО делает лишние преобразования для записи в бд

2022-07-29 10:29 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +    }
Да, все использованы

2022-07-29 10:36 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/db/models/ListModel.java
> +    }
Будет создана модель с пустыми полями, а хедер будет инициализирован со значением null

2022-07-29 10:38 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +        }
Да, можно сделать метод с названием по типу "convertListItemModelsToListItems"

2022-07-29 10:40 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +        );
Можно сделать метод, который будет получать модель и возвращать dto

2022-07-29 10:54 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +    public void insertListItem(int listID, String listItemDescription) {
> Можно ли сделать так, чтобы id назначалось БД, а не в приложении?

Думаю реализовать можно в DAO. При создании объекта будет назначаться модели id, который выдает автоматически sqlite и в репозитории уже будет преобразование в обычный ListItem.

> И чем плохо, если задача назначение ID лежит на приложении?

Тем, что например при удалении списка id не уменьшатся на 1, а останутся статичными. Т.е. если удалить из списков 1-9 список с id = 8, то остальные не поменяются и реализацию выдачи id приложением сделать уже становится трудным.

2022-07-29 10:57 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/detailscreen/DetailedListViewModel.java
> +                                 String listHeader) {
Да, можем, то есть 4-й параметр здесь особо и не нужен

2022-07-29 10:59 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/listscreen/ListViewModel.java
>      }
Я думал, где сделать переход к конкретной реализации, и пришел к выводу, что вьюмодель не связана с DAO, что внесло бы путаницы, если бы в качестве параметра я передавал его, а не контекст. А репозиторий имеет связь с DAO, поэтому я посчитал, что тут будет уместно сделать переход к реализации от абстракции.

2022-07-29 11:00 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +        ListModel listModel = new ListModel();
Конкретной причины нет, скорее это привычка объявлять локальные переменные в начале метода/функции

2022-07-29 11:34 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +            }
https://www.javatpoint.com/java-do-while-loop

2022-07-29 11:35 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +        ListModel listModel = new ListModel();
Лучше используй подходящий для этого конструктор.

2022-07-29 11:36 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
> +        String newStateString = (listItem.is_checked) ? "1" : "0";
SRP, у тебя твой метод отвечает за взаимодействие с БД и за подготовку данных для БД (конвертация Bool в Int).

2022-07-29 11:39 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListModel.java
> +    }
А точно, это же джава) Я намекал, что у нас всё должно быть не null, если другого не указано. Но этот конструктор уйдёт, когда ты поправишь [этот коммент](https://github.com/ShinyParadise/ToDoList/pull/3#discussion_r932189801).

2022-07-29 11:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listitemsrepository/ListItemRepository.java
> +    public void insertListItem(int listID, String listItemDescription) {
> Думаю реализовать можно в DAO. При создании объекта будет назначаться модели id, который выдает автоматически sqlite и в репозитории уже будет преобразование в обычный ListItem.

Очень часто делают так, что метод `insert`, `add`, `create` возвращают переданную сущность с уже назначенным id.

> Тем, что например при удалении списка id не уменьшатся на 1, а останутся статичными. Т.е. если удалить из списков 1-9 список с id = 8, то остальные не поменяются и реализацию выдачи id приложением сделать уже становится трудным.

Не совсем, тут всё немного проще, ответственность за эту логику ложится на твой код, следовательно, нужно покрывать эту логику тестами, чтобы убедиться в её работоспособности. Также это "велосипед", который уже реализован в sqlite. И в заключение, если код можно не писать, то лучше его не писать (любой написанный код, это потенциальный источник проблем).

2022-07-29 11:49 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/listscreen/ListViewModel.java
>      }
Тут происходит нарушение инверсии зависимотей, так как мы создаём непосредственно сами объекты. Что бы было, если мы создали новый репозиторий, который уже не зависит от DAO?

2022-08-01 09:12 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/listscreen/ListViewModel.java
>      }
> Тут происходит нарушение инверсии зависимостей, так как мы создаём непосредственно сами объекты. Что бы было, если мы создали новый репозиторий, который уже не зависит от DAO?

Тогда бы пришлось переписывать лишний раз код, где нужен такой репозиторий. Я так понял, что во вьюмодель нужно передавать не контекст, а репозиторий

2022-08-01 09:14 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/listitem/ListItemDAO.java
> +        String newStateString = (listItem.is_checked) ? "1" : "0";
Понятно, тогда стоит просто сделать ее int'овой

2022-08-01 13:38 UTC, menteValidus requested changes

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/list/ListDAO.java
> +        );
На 46-50, 53-67 и 82-85 строках дублирование кода. Как от него избавиться?

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +                listItems.add(newListItem);
Какие задачи выполняет этот код? Можно ли это упростить так, чтобы они были видны явно?

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
Дублирование кода с 35-38

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
Также дублирование. В чём будет проблема этого дублирования?

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/DatabaseContract.java
> +    );
Здесь стоит проблема читаемости. Первый вариант более читаемый, чем второй, но всё же код довольно сложно прочесть. Попробуй сделать составление запроса максимально читаемым, используй инструменты [конкатенации строк](https://www.techiedelight.com/concatenate-two-strings-java/) в Java.

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/listScreen/ListsFragment.java
> +                        adapter.getToDoLists().get(position)
Почему ты получаешь данные из адаптера, а не из ViewModel? Какая проблема может возникнуть?

2022-08-01 13:38 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/listScreen/ListsFragment.java
> +                        adapter.getToDoLists().get(position)
И также, в чём состоит роль адаптера?

2022-08-04 08:57 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/listScreen/ListsFragment.java
> +                        adapter.getToDoLists().get(position)
> Почему ты получаешь данные из адаптера, а не из ViewModel? Какая проблема может возникнуть?

Список адаптера может отличаться от списка во ViewModel, это дополнительная головная боль, когда нужно следить за обновлением данных в двух местах сразу. 

> И также, в чём состоит роль адаптера?

Он нужен для того, чтобы создавать ViewHolder'ы и определять какие данные в них должны отображаться. Получается я здесь приписал дополнительную роль адаптеру, чего делать не стоило. Эти данные должны вытягиваться из ViewModel

2022-08-04 08:59 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
В этих строчках тяжело разобраться, если не знать как устроена бд, т.е. с ходу не понять что будет соответствовать параметру конструктора. И эти строчки повторяются для другой сущности, только с другой комбинацией, это тоже усложняет понимание происходящего

2022-08-04 09:06 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +                listItems.add(newListItem);
Здесь происходит преобразование данных взятых из бд в модель, после чего она добавляется в список всех айтемов. Можно эту логику инкапсулировать в метод с названием типа "parseListItemModelFromDB"

2022-08-04 09:08 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
Не совсем, ещё варианты?

2022-08-04 09:47 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +                listItems.add(newListItem);
Можно даже просто `toListItem()`.

2022-08-04 09:55 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
Проблема в том, что нужно каждый раз заново прописывать параметры из реквеста, а отдельным методом будет реюзабельно и понятнее?

2022-08-04 09:57 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dao/listItem/ListItemDAO.java
> +        );
Да

2022-08-04 12:16 UTC, menteValidus approved these changes

2022-08-04 12:17 UTC, merged