Sorting feature
ShinyParadise/ToDoList pull request #4
Opened 2022-08-08 11:40 UTC by ShinyParadise

2022-08-08 12:46 UTC, menteValidus requested changes

2022-08-08 12:46 UTC, menteValidus commented on app/build.gradle
> +        minSdk 26
Зачем тебе это нужно?

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/DatabaseContract.java
> +
Эта строка нужна только для миграции. Во-первых, как мне понять? Во-вторых, допустим, за всю жизнь приложения мы написали 10 миграций. Какая проблема у нас всплывёт?

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +        this.last_update = last_update;
Можешь ещё использовать неплохое название `updatedAt`.

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +        this.last_update = last_update;
Только сейчас заметил, почему ты смешиваешь camelCase со snake_case? Какой подход предпочтительнее для джавы?

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dto/ListItem.java
> +    private LocalDateTime lastUpdate;
Почему LocalDateTime?

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dto/ListItem.java
> +        this.lastUpdate = lastUpdate;
Смешал camelCase со snake_case

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listItemsRepository/ListItemRepository.java
> +    }
Зачем тебе это? Расскажи мне, что такое `ZonedDateTime`, `LocalDateTime` и `Instant`? Чем они конкретно различаются? Как один тип преобразовать в другой?

2022-08-08 12:46 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/detailScreen/DetailedListViewModel.java
> +    }
Почитай эту доку и расскажи как будет сделать это правильнее?
https://www.geeksforgeeks.org/collections-sort-java-examples/

2022-08-08 13:59 UTC, ShinyParadise commented on app/build.gradle
> +        minSdk 26
Когда я использовал методы из библиотеки `java.time`, студия жаловалась, что они будут работать минимально с этой версии sdk.

2022-08-08 14:03 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/db/DatabaseContract.java
> +
Чтобы понять суть можно исправить название запроса на `MIGRATE_TO_VERSION_2`. Если будет много миграций, то будет много запросов, который делают миграцию данных, в них будет сложно разобраться. Может логику миграций стоит инкапсулировать?

2022-08-08 14:06 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +        this.last_update = last_update;
Я так хотел выделить классы моделей, чтобы они отличались от классов DAO. А так для джавы предпочтительнее camelCase

2022-08-08 14:12 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/dto/ListItem.java
> +    private LocalDateTime lastUpdate;
Я подумал что необязательно хранить часовой пояс. В единственном месте, где создаются и конвертируются даты, таймзона учитывается и берется из устройства

2022-08-08 14:26 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/repositories/listItemsRepository/ListItemRepository.java
> +    }
Я использовал метод из `ZonedDateTime` для того, чтобы учесть таймзону при создании `LocalDateTime`.
`ZonedDateTime` - временная метка с часовым поясом (т.е. в строковом виде добавится "Russia/Moscow").
`LocalDateTime` - временная метка без часового пояса как у `ZonedDateTime`, однако может зависеть от него (строка вида "2022-08-08T00:00").
`Instant` - тоже временная метка, обозначает количество миллисекунд, без привязки к часовому поясу, т.е. всегда используется UTC. 
Конвертация из одного класса в другой производится добавлением (для `ZonedDateTime`) или отбрасыванием таймзоны (для `LocalDateTime` отбрасывается часть строки, но время можно взять относительно какой-то таймзоны).

2022-08-08 14:32 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/detailScreen/DetailedListViewModel.java
> +    }
Правильнее сделать класс наследующий интерфейс Comparator<ListItem> и прописать метод сортировки в нем. Так можно сделать код для сортировки айтемов реюзабельным

2022-08-09 10:22 UTC, menteValidus commented on app/build.gradle
> +        minSdk 26
Поищи способ использовать эту библиотеку с api 21. И расскажи, когда и зачем мы можем поднимать версию api?

2022-08-09 10:23 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/DatabaseContract.java
> +
> Может логику миграций стоит инкапсулировать?

Да, хорошая мысль.

2022-08-09 10:24 UTC, menteValidus commented on app/src/main/java/com/example/todolist/db/models/ListItemModel.java
> +        this.last_update = last_update;
Лучше всегда придерживаться одного подхода. Для именования переменных мы используем camelCase.

2022-08-09 10:44 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dto/ListItem.java
> +    private LocalDateTime lastUpdate;
Это связано с этим [комментарием](https://github.com/ShinyParadise/ToDoList/pull/4#discussion_r940187870). Просто получается, что вне зависимости от использования LocalDateTime мы вынуждены использовать ZonedDateTime для сохранения в БД. Этого можно избежать просто используя ZonedDateTime.

2022-08-09 10:47 UTC, menteValidus commented on app/src/main/java/com/example/todolist/dto/ListItem.java
> +    private LocalDateTime lastUpdate;
Лично я использую эти сущности так, `ZonedDateTime` в целом по приложению, `LocalDateTime` на местах с коротким жизненным циклом, если это необходимо, `Instant` для сохранения дат как число в БД.

2022-08-09 10:56 UTC, menteValidus commented on app/src/main/java/com/example/todolist/ui/detailScreen/DetailedListViewModel.java
> +    }
Да, выдели в отдельную сущность и напиши для неё тесты. Также прочитай про `compareTo` метод и скажи, где его можно использовать?

2022-08-10 08:58 UTC, ShinyParadise commented on app/build.gradle
> +        minSdk 26
Версию API можно поднять, если в бизнес логике невозможно обойтись без каких-либо фич более высокой версии апи (либо невозможно их заменить), и это принесет большую выгоду, чем расширение рынка за счет более низкой версии API. Это обычно решается не разработчиком, а PM-ом, как я думаю

2022-08-10 09:11 UTC, ShinyParadise commented on app/src/main/java/com/example/todolist/ui/detailScreen/DetailedListViewModel.java
> +    }
`compareTo` можно использовать как упрощение логики в компараторе, меньше строчек и понятнее другим людям

2022-08-11 10:04 UTC, menteValidus commented on app/build.gradle
> +        minSdk 26
Да, если это того стоит. В целом, обычно версии повышаются по мере отказа и уменьшения кол-ва пользователей на определённом API. Очень редко это делается из-за новых фич.

2022-08-11 10:13 UTC, menteValidus approved these changes

2022-08-11 10:13 UTC, menteValidus commented on app/src/main/java/com/example/todolist/repositories/listItemsRepository/ListItemRepository.java
> +import java.util.TimeZone;
Не забывай чистиь ипморты.

2022-08-11 10:15 UTC, merged